spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/acme
    driver-class-name: org.postgresql.Driver
    username: acme
    password: acme
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true