CREATE SCHEMA IF NOT EXISTS acme_app;

GRANT ALL ON SCHEMA acme_app TO acme;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA acme_app TO acme;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA acme_app TO acme;